### ISSUE TITLE
Unable to make pw.x file

### ISSUE THREAD

**Issue by benagastov** [sedaoturak/Quantum_Espresso_Colab#1]
I tried to run your colab in repository, but i don't know why the Colab didnt want to make pw file. It seems something happen with the configuration or gfortran or original quantum espresso github version.

**Comment by benagastov** [comment]
Here is the log from the colab
[errorlog.txt](https://github.com/sedaoturak/Quantum_Espresso_Colab/files/12506259/errorlog.txt)

**Comment by sedaoturak** [comment]
I tried to run and got the same error. I'm looking into this, bu haven't able to find the solution yet. It might be related to QE package itself, I'm not sure if it's updated recently. If I can find something, I'll make an update.

**Comment by benagastov** [comment]
Thank you for your help, I browse some forums trying to find same error code. Some answers told me that perhaps its because newer CUDA version is not compatible, or new version of Fortran is not compatible. Installing older version of QE and fortran is possible, but I still get another error. I also will look for another possible solutions. Thank you very much for your attention

**Comment by kokiyaita** [comment]
Hello! I'm also having same issue. I remember that I was using your Colab Notebook without any problems until July 2023. There were updates on the Google Colab servers. Please see the below link to check the detail of the update.
I'm not sure what caused the problem but I hope it helps a little bit.
https://colab.research.google.com/notebooks/relnotes.ipynb

**Comment by sedaoturak** [comment]
Thank you for sharing this! This might be due to this update -it comes to some dates.
I also have some issues in other packages on colab, too. If I can find a solution for this, I'll make an update.

**Comment by sedaoturak** [comment]
Good news! I changed configuration settings during the installation of QE and it seems that it's working.
Updated the notebook.

**Comment by kokiyaita** [comment]
@sedaoturak Thank you very much for your amazing work! I also tested the notebook and it seems working perfectly! I'd really appreciate that.
